server:
  port: 8060

spring:
  application:
    name: car-rental-api
  h2:
    console:
      enabled: true
      settings.web-allow-others: true
  datasource:
    url: jdbc:h2:mem:cars;DATABASE_TO_UPPER=false
#    url: jdbc:h2:file:/data/demo # use this line to persist data
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true # create tables before populating them
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: embedded # always | never | embedded

logging:
  level:
    root: info
    it:
      unitn: trace
    org:
      springframework:
        security: debug # info | debug

management:
  endpoints:
    web:
      exposure:
        include: mappings, beans, health